
export { default as fontSize } from './fontSize';
export * from './fontSize';
export * from './colors';
export * from './styles';
export { default as font } from './font';
export * from './font'
export * from './size'
export {
    CNeutral,
    CNeutral1,
    CNeutral2,
    CNeutral3,
    CNeutral4,
    CNeutral5,
    CNeutral6,
    CNeutral7,
    CNeutral8,
    CNeutral9,
    CNeutral10,
    CNeutral11,
    CNeutral12,
    CNeutral13,
    CPrimary,
    CPrimary1,
    CPrimary2,
    CPrimary3,
    CPrimary4,
    CSecondary,
    CSecondary1,
    CSecondary2,
    CSecondary3,
    CSecondary4,
    CTextLight,
    CTextLight1,
    CTextLight2,
    CTextLight3,
    CTextLight4,
    CTextLight5,
    CTextLight6,
    CTextLight7,
    CTextDark,
    CTextDark1,
    CTextDark2,
    CTextDark3,
    CTextDark4,
    CTextDark5,
    CTextDark6,
    CTextDark7,
    CLink,
    CSuccess,
    CWarning,
    CError,
    backgroundColor,
    color,
  } from './colors'
